# Welcome to PyRun!

# Need to install more packages? Just edit this file.

# Add packages from conda-forge under "dependencies:"
# Packages from PyPI should be added under "pip:"

name: test3
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - git
  - dask
  - dask-cloudprovider
  - zarr
  - xarray
  - s3fs
  - gcsfs
  - cftime
  - matplotlib
  - esmpy 
  - numpy 
  - shapely 
  - cf_xarray 
  - sparse 
  - numba
  - tqdm
  - pip:
    - git+https://github.com/pangeo-data/xesmf.git
    - cartopy
    - intake-esm
